version: '3.8'

services:
  timemachine:
    build: .
    container_name: timemachine
    environment:
      HOME_ASSISTANT_URL: ${HA_URL}
      LONG_LIVED_ACCESS_TOKEN: ${HA_TOKEN}
      NODE_ENV: development
    hostname: timemachine
    networks:
      docker1:
        ipv4_address: ${HOST_IP}
    ports:
      - 54000:54000
    restart: always
    volumes:
      - data:/data
      - media:/media
      - /var/lib/docker/volumes/homeassistant_config/_data:/config:ro

networks:
  docker1:
    name: docker1
    external: true

volumes:
  data:
    driver: local
  media:
    driver: local
